name: CI

on:
  push:

jobs:
  check:
    runs-on: ubuntu-latest
    container: oven/bun:alpine
    steps:
      - uses: actions/checkout@v4
      - run: bun install --frozen-lockfile
      - run: bun run build:types
      - run: bun run lint
      - run: bun test
